services:
    postgres:
        image: bitnami/postgresql:latest
        environment:
            - POSTGRESQL_USERNAME=${DB_USER:-postgres}
            - POSTGRESQL_PASSWORD=${DB_PASS:-postgres}
            - POSTGRESQL_DATABASE=${DB_NAME:-mydatabase}
            - POSTGRESQL_PORT_NUMBER=${DB_PORT:-5432}
        volumes:
            - postgres-data:/bitnami/postgresql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
        networks:
            - shared_net


    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@example.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        ports:
            - "8080:80"
        networks:
            - shared_net


volumes:
    postgres-data:
        driver: local
    pgadmin-data:
        driver: local

networks:
    shared_net:
        external: true